version: '3.0'

services:
  web:
    command:
      - |
        echo "if you're watching this, please fire me... "
        python /app/manage.py makemigrations
        python /app/manage.py migrate
        echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'a@a.com', 'vanevan3')" | python /app/manage.py shell
        python /app/manage.py runserver 0.0.0.0:8000
