version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: . 
    ports:
      - '8000:8000'
    entrypoint: ["/bin/sh","-c"]
    command: 
      - |
        echo "if you're watching this, please fire me... "
        python /app/manage.py makemigrations
        python /app/manage.py migrate
        echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'a@a.com', 'vanevan3')" | python /app/manage.py shell
        python /app/manage.py runserver 0.0.0.0:8000
        # echo "mental note in a yml cuz why not > replace all this shit with gunicorn, fixing /statics."
        # gunicorn --bind :8000 config.wsgi:application
    volumes:
      - ./app/:/app
      - ./remote-vscode:/root/.vscode-server/extensions
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
